source 'https://rubygems.org'

# https://github.com/bundler/bundler/issues/4978
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '6.1.4'
gem 'sidekiq'

# server
gem 'bootsnap', require: false
gem 'puma'

# database
gem 'hirb'
gem 'jsonb_accessor'
gem 'pg'

# assets
gem 'font_awesome5_rails'
gem 'haml-rails'
gem 'sassc-rails'
gem 'turbolinks'

# app
gem 'country_select'
gem 'countries'
gem 'devise'
gem 'faker'
gem 'pundit'
gem 'state_machines-activerecord'
gem 'activeadmin'

# admin charts https://github.com/ankane/chartkick
gem "chartkick"
gem 'groupdate'

## paypal
gem 'ianfleeton-paypal-express', github: 'ianfleeton/paypal-express', require: 'paypal/express'
# stripe
gem 'stripe'
# pdf for receipts
gem 'wicked_pdf' # https://github.com/mileszs/wicked_pdf
gem 'wkhtmltopdf-binary'

# api
gem 'faraday'
gem 'grape'
gem 'grape-entity', github: 'ruby-grape/grape-entity', branch: 'master'

# cron job https://fuzzyblog.io/blog/rails/2017/05/11/adding-cron-to-a-dockerized-rails-application-using-clockwork.html
# https://github.com/adamwiggins/clockwork
gem 'clockwork'

# qr-code https://github.com/whomwah/rqrcode
gem 'rqrcode'
# error catcher https://github.com/smartinez87/exception_notification
gem 'exception_notification'

# ancestry https://github.com/stefankroes/ancestry
gem 'ancestry'

group :development do
  gem 'grape_on_rails_routes'
  gem 'letter_opener'
  gem 'seedbank'
  gem "rails-erd"
end

group :development, :test do
  gem 'factory_bot_rails'
  gem 'fix-db-schema-conflicts'
  gem 'pry-byebug'
end

group :test do
  gem 'database_cleaner'
  gem 'guard-rspec'
  gem 'pundit-matchers'
  gem 'rails-controller-testing'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'state_machines-rspec'

  # stripe-mock is a mock HTTP server that responds like the real Stripe API
  # https://github.com/stripe-ruby-mock/stripe-ruby-mock
  gem 'stripe-ruby-mock', '~> 3.1.0.rc3', :require => 'stripe_mock'

  gem 'capybara'
  gem 'fakeredis'
  gem 'launchy'
  gem 'selenium-webdriver'
  # check if the release is out yet https://github.com/thoughtbot/shoulda-matchers/milestone/13
end
